### ISSUE TITLE
The .Base package should be exposed

### ISSUE THREAD

**Issue by bos** [haskell-unordered-containers/unordered-containers#103]
Without e.g. `unsafeInsert` being exposed, I have no way to roll my own efficient construction function.

**Comment by tibbe** [comment]
If the construction function is useful enough perhaps we could put it in the package itself? What does it do? I'm also open to exposing some unsafe module that people can build on top of. For example, I've been thinking of exposing an `ST` module with a `freeze` function.

**Comment by bos** [comment]
It wants to be a hand-rolled version of the `fromList` function, where I'm building (but never looking at) a `HashMap` on the fly as a parser runs.

You can see what I'm getting at in [line 124 of this commit](https://github.com/bos/aeson/commit/96d070dea871c6ad13aba7f1b33e5abe3c891765#diff-88bde784dd47e1b7a145bf6c3acbd2deR124#L124).

**Comment by tibbe** [comment]
Would it be OK if `unsafeInsert` was exposed in `ST`? It would probably require that you used some monad transformer (or simply called `runST`). I'm a bit dubious about its safety aspects (e.g. if it ever got hoisted) given its current definition.

**Comment by bos** [comment]
Unfortunately ST is not an option, as the parser in question is attoparsec,
and I can't rearchitect all of attoparsec to accomodate this.

**Comment by bos** [comment]
Here's what I'll try instead: I'll hack up a local `unordered-containers` that *does* expose `unsafeInsert` and benchmark it. If it actually helps performance, we've maybe got a case for a `.Unsafe` module – and if not, there's no more need for a conversation :-)

**Comment by tibbe** [comment]
SGTM

**Comment by winterland1989** [comment]
I want to bump up this issue for exactly the same reason, i found `fromList` is faster than repeat inserts, but by exporting `unsafeInsert` we can eliminate intermedia list.

**Comment by sjakobi** [comment]
Regarding `unsafeInsert`, how about exposing it from the public API?

It doesn't look like a function that we'd want to change between minor versions and therefore preferably exclude from the usual PVP versioning.

**Comment by tibbe** [comment]
I think @bos comment above about benchmarking and showing an improvement on something is a step in the right direction.

**Comment by sjakobi** [comment]
As of https://github.com/haskell-unordered-containers/unordered-containers/commit/6f1a92f6cc9fe817661ba5dc56bf609a5145d683, `unsafeInsert` is exported from `Data.HashMap.Internal`.

I'll tentatively close this issue. If there's demand for further discussion on `unsafeInsert`, I'd suggest opening a new issue for that.
