### ISSUE TITLE
Add specialized traversals for IO and ST

### ISSUE THREAD

**Issue by treeowl** [haskell-unordered-containers/unordered-containers#151]
The `Traversable` instance for `Array` is unavoidably wasteful for basically the same reason that GHC can never apply list fusion to the result of `traverse @[]`. I think it would be nice to offer specializations of the `HashMap` `traverse` to `IO` and `ST` (strict `ST`, at least). The `ST` traversal for `Array` looks like this:

```haskell
traverseST :: (a -> ST s b) -> Array a -> ST s (Array b)
traverseST f = \ xs ->
  let
    lxs = length xs

    go mary i
      | i == lxs = unsafeFreeze mary
      | otherwise = do
          x <- indexM xs i
          x' <- f x
          write mary i x'
          go mary (i + 1)
  in do
       mary <- new_ lxs
       go mary 0
{-# INLINE traverseST #-}
```
The `HashMap` version would be the same as `traverse` but would use `A.traverseST` or `A.traverseIO`.

It would probably also make sense to add rewrite rules to use these functions where applicable.

**Comment by treeowl** [comment]
Another option might be to use a `PrimBase` constraint.

**Comment by tibbe** [comment]
If a `SPECIALIZE` implementation makes things faster I'm happy to take a pull request!

**Comment by treeowl** [comment]
SPECIALIZE  won't help any. RULES should do the trick. But I think it would
be nice to also export a function users can use directly.

**Comment by andrewthad** [comment]
I think it should be possible to add the rewrite rule for `Data.HashMap.Array.traverse` and then add the `SPECIALIZE` pragma for `traverseWithKey` so that the logic in that function there doesn't end up duplicated. You might have to fiddle with the phase that `traverse` would inline in to make this work.

**Comment by sjakobi** [comment]
`traverseST` and `traverseIO` exist now (but are untested: https://github.com/haskell-unordered-containers/unordered-containers/issues/272)

https://github.com/haskell-unordered-containers/unordered-containers/blob/964edca40d415c7f0b70c99fda2a4d9dc0949b9f/Data/HashMap/Array.hs#L575-L619

Please reopen if there's more to do here.
