### ISSUE TITLE
The Ord instance is not obvious; it could use documentation

### ISSUE THREAD

**Issue by treeowl** [haskell-unordered-containers/unordered-containers#152]
@phadej, what does the comparison mean, if anything? That should be documented. One case in `cmp` is surprising:

```haskell
    go (Collision k1 ary1 : tl1) (Collision k2 ary2 : tl2)
      = compare k1 k2 `mappend` compare (A.length ary1) (A.length ary2) `mappend`
        unorderedCompare leafCompare (A.toList ary1) (A.toList ary2)
```

I don't know anything about array-mapped tries, but I would think this deserves a comment to explain why `tl1` and `tl2` are unused. Assuming they're *supposed* to be unused, they should also get underscore prefixes.

**Comment by sjakobi** [comment]
At least the issue of `tl1` and `tl2` was addressed in https://github.com/haskell-unordered-containers/unordered-containers/commit/450bf5e0a8a5e001c72fca34023ecfd81e6cdcf7.

There's probably more to do but that should be clarified in a new issue.
