### ISSUE TITLE
Simplify unionWithKey

### ISSUE THREAD

**Issue by treeowl** [haskell-unordered-containers/unordered-containers#227]
I strongly suspect that we can lift the `go` worker in `insertModifying` to the top level and use it to implement all seven cases in `unionWithKey` where one of the arguments is a leaf.

**Comment by treeowl** [comment]
Hrm.... It's trickier than that. If `m` doesn't contain `k`, and we're combining `t@(Leaf h l@(L k v))` with `m`, we can usually reuse `t` and the rest of the time we can reuse  `l`. Using `insertModifying`, we'd end up allocating a lot of new `Leaf` and `L` constructors, to the tune of something like six words per entry. That's a bit too steep. But I think it may still make sense to try to tease these things apart a bit.

**Comment by sjakobi** [comment]
Superseded by #285.
