### ISSUE TITLE
Strictness properties missing in documentation

### ISSUE THREAD

**Issue by leonschoorl** [haskell-unordered-containers/unordered-containers#238]
The haddock of Data.HashMap.Strict has a heading [Strictness properties] but no properties.

They seem to have been deleted here: https://github.com/tibbe/unordered-containers/pull/186/files#diff-1b71e586508ac38a4157ee51fdc2def7L115

[Strictness properties]: https://hackage.haskell.org/package/unordered-containers-0.2.10.0/docs/Data-HashMap-Strict.html#g:1

**Comment by treeowl** [comment]
Whoops! Thanks for the heads up.

**Comment by sjakobi** [comment]
Fixed in #255, I believe? Otherwise, please reopen.
