### ISSUE TITLE
unionsWith

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell-unordered-containers/unordered-containers#240]
`unionsWith` would be a nice addition

`unionsWith :: Foldable f => (NonEmpty a -> b) -> f (HashMap k a) -> HashMap k b`

**Comment by sjakobi** [comment]
Oh, I just noticed that the type signature you're requesting is not the same as in #118:

```
unionsWith :: (Eq k, Hashable k) => (v -> v -> v) -> [HashMap k v] -> HashMap k v
```

That one is somewhat closer to the one in containers though:

```
unionsWith :: (Foldable f, Ord k) => (a -> a -> a) -> f (Map k a) -> Map k a
```

**Comment by BebeSparkelSparkel** [comment]
I still want the `a -> b` transformation for one or more.

**Comment by sjakobi** [comment]
Yeah, that would be nice to have. https://github.com/haskell-unordered-containers/unordered-containers/issues/226 seems like a good road towards that feature. Feel free to chime in there!

**Comment by sjakobi** [comment]
@BebeSparkelSparkel I'm somewhat confused by your comment https://github.com/haskell-unordered-containers/unordered-containers/issues/226#issuecomment-647064798.

Could you maybe give us some context regarding the problem you want to solve, so we can better understand your requirements?

**Comment by BebeSparkelSparkel** [comment]
Detailed in #244, was my usecase, but switched data structures. However, this still seemed like a useful feature for combining a lot of small mappings. This allows the functions generating the mappings to be more compartmentalized by returning a mapping instead of having to pass a mapping into it and then returning the modified mapping. The downside is that I get all these maps that take up a whole bunch of space that cannot be garbage collected which I was trying to avoid with the fold, #226. I'll close this and defer to #226. I'm quite busy right but @sjakobi if you need some help/review with #226 let me know.
