### ISSUE TITLE
unionWith of different value types

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell-unordered-containers/unordered-containers#242]
`unionWith` seems like it would be more useful and could be used in folds if it had the type

`unionWith :: (Eq k, Hashable k) => (a -> b -> c) -> HashMap k a -> HashMap k b -> HashMap k c`

Would you consider changing the type or adding it as `unionWith'`?

**Comment by treeowl** [comment]
That type doesn't work. You'd need two more function arguments: `a -> c` and `b -> c`. I'd rather add a `containers`-like merge mechanism.

**Comment by BebeSparkelSparkel** [comment]
http://hackage.haskell.org/package/containers-0.6.2.1/docs/Data-Map-Merge-Strict.html#v:merge
`merge` definitely seems better

**Comment by sjakobi** [comment]
Since there seems to be a consensus that a `containers`-style `merge` function as requested in #226 would be the better addition, I'll tentatively close this as a duplicate. Please reopen, if you disagree.
