### ISSUE TITLE
Editing errors render note on (Ord k, Ord v) => Ord (HashMap k v) instance difficult to decipher

### ISSUE THREAD

**Issue by tmcl** [haskell-unordered-containers/unordered-containers#250]
The Ord instance for HashMap says:

> (Ord k, Ord v) => Ord (HashMap k v)
> 
> The order is total.
> 
> Note: Because the hash is not guaranteed to be stable across library versions, OSes, or architectures, neither is an actual order of elements in HashMap or an result of compare.is stable.

Unfortunately that sentence is incoherent and I cannot reliably recover the intended meaning. I think it's meant to be "Note: Because the hash is not guaranteed to be stable across library versions, OSes or architectures, neither is an actual order of elements in HashMap or a result of `compare` stable."

If that is the intended meaning I might propose:

> Note: The actual order of elements in HashMap and the result of `compare` is not stable since the hash is not guaranteed to be stable across library versions, OSes or architectures

since this avoids a conjunction of a list coinciding with a conjunction of clauses and complex grammatical reorderings.

**Comment by sjakobi** [comment]
Related to https://github.com/haskell-unordered-containers/unordered-containers/issues/152.

**Comment by sjakobi** [comment]
It would be great to fix this, although I don't currently understand the instance sufficiently to say whether the wording you propose, @tmcl, is correct.

I think there might be a connection to #231, but I might be wrong.

I think it would be best to discuss this on a PR. @tmcl, would you possibly consider preparing one?
