### ISSUE TITLE
Is it beneficial for HashMap to mimic Python dict's behavior of insertion order reservation?

### ISSUE THREAD

**Issue by complyue** [haskell-unordered-containers/unordered-containers#253]
CPython borrowed the dict implementation from PyPy since 3.6:

https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-compactdict

```rst
New :ref:`dict <typesmapping>` implementation
---------------------------------------------

The :ref:`dict <typesmapping>` type now uses a "compact" representation
based on `a proposal by Raymond Hettinger
<https://mail.python.org/pipermail/python-dev/2012-December/123028.html>`_
which was `first implemented by PyPy
<https://morepypy.blogspot.com/2015/01/faster-more-memory-efficient-and-more.html>`_.
The memory usage of the new :func:`dict` is between 20% and 25% smaller
compared to Python 3.5.

The order-preserving aspect of this new implementation is considered an
implementation detail and should not be relied upon (this may change in
the future, but it is desired to have this new dict implementation in
the language for a few releases before changing the language spec to mandate
order-preserving semantics for all current and future Python
implementations; this also helps preserve backwards-compatibility
with older versions of the language where random iteration order is
still in effect, e.g. Python 3.5).

(Contributed by INADA Naoki in :issue:`27350`. Idea
`originally suggested by Raymond Hettinger
<https://mail.python.org/pipermail/python-dev/2012-December/123028.html>`_.)
```

Python language made it official behavior since 3.7:

https://docs.python.org/3.7/whatsnew/3.7.html

```rst
Python data model improvements:

* ...

* ...

* the insertion-order preservation nature of :ref:`dict <typesmapping>`
  objects `has been declared`_ to be an official
  part of the Python language spec.

.. _has been declared: https://mail.python.org/pipermail/python-dev/2017-December/151283.html
```

I don't know enough details to triage whether it'll profit performance-wise to borrow the idea to the implementation of HashMap in Haskell. Or it is even feasible at all?

**Comment by treeowl** [comment]
Can you try to explain what behavior this refers to?

**Comment by complyue** [comment]
For example in Python:

```python
>>> dict(d=3, b=2, a=7, c=1)
{'d': 3, 'b': 2, 'a': 7, 'c': 1}
>>> {'d': 3, 'b': 2, 'a': 7, 'c': 1}
{'d': 3, 'b': 2, 'a': 7, 'c': 1}
>>> 
>>> d = {}
>>> d['d'] = 3
>>> d['b'] = 2
>>> d['a'] = 7
>>> d['c'] = 1
>>> d
{'d': 3, 'b': 2, 'a': 7, 'c': 1}
>>> 
```

If you insert entries into a dict by keys in order as 'd', then 'b', then 'c', then 'a', it's guaranteed you'll get the entries out of that dict in exact the same order as the dict is iterated against:

```python
>>> [(k, v) for (k, v) in d.items()]
[('d', 3), ('b', 2), ('a', 7), ('c', 1)]
>>> 
```

In Haskell we get that guaranteed order by modeling mapping with list just like `[('d', 3), ('b', 2), ('a', 7), ('c', 1)]`, and we approach O(1) key lookup with HashMap, while Python dict has both property.

**Comment by treeowl** [comment]
I have no idea how Python might be accomplishing that, but it must be using a different data structure altogether, or augmenting a hash map with some other data structure. Regardless, there will be serious performance implications. We're not going to attempt to copy the Python behavior in this package.
