### ISSUE TITLE
alterF is untested

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#273]
Both the strict and lazy variants, that is.

Related: #270.

**Comment by sjakobi** [comment]
…at least the default variant is:

![image](https://user-images.githubusercontent.com/3664523/85204738-c260d600-b316-11ea-8118-c2cabfab5e31.png)

`alterFEager` has better test coverage.

**Comment by treeowl** [comment]
@sjakobi I've deleted your last comment as a matter of policy (which we should write down somewhere). No images of text allowed; they are inaccessible to blind contributors.

**Comment by sjakobi** [comment]
@treeowl Please don't simply delete my comments without my consent. At least you could preserve the information within in a more accessible format if you need to.

Let's also discuss this policy on a separate issue first. Are any existing contributors visually impaired?

**Comment by treeowl** [comment]
Sorry. I'll give the next person who does that a brief warning first. I expect you won't make that mistake again. Whether we currently have blind contributors or blind people interested in our activities is irrelevant. Pictures of text are *gratuitously* inaccessible, and bad for the whole Internet.

**Comment by treeowl** [comment]
Sorry I'm being snappish, but this is an important issue for me and I don't have much patience left for it. It's not hard: copy and paste; don't screenshot.

**Comment by sjakobi** [comment]
@treeowl If you're mad at me for some reason, let's talk about it. How about a video or voice chat in the next few days?

Not right now though – your disrespect for my contributions makes me rather angry.

**Comment by sjakobi** [comment]
If I remember correctly, it was only the simple default implementation that is untested. The `alterFWeird` version used by the RULES is tested.
