### ISSUE TITLE
Please expose `HashMap.Base` & other internal modules

### ISSUE THREAD

**Issue by jamespayor** [haskell-unordered-containers/unordered-containers#280]
If I want to write some inner-loop code that wants access to the innards of `HashMap`, there's currently no way I see to do so, because the constructors and internal methods are only in hidden modules:

```cabal
library
  exposed-modules:
    Data.HashMap.Lazy
    Data.HashMap.Strict
    Data.HashSet
  other-modules:
    Data.HashMap.Array
    Data.HashMap.Base
    Data.HashMap.Strict.Base
    Data.HashMap.List
    Data.HashMap.Unsafe
    Data.HashMap.UnsafeShift
    Data.HashSet.Base
```

Would you be able to instead expose these? Or at least, expose `Data.HashMap.Base`/`Data.HashMap.Strict.Base`/`Data.HashSet.Base`?

----

I think it's fair game for these modules to be subject to arbitrary breaking changes through versions, but it would be nicer for me as an end user to be able to get at the internals without forking the package.

For instance, for a container type I'm implemented, I wanted to be able to enumerate the items of a `HashMap` including the precalculated hashes. Something like `toHashedList :: HashMap k v -> [(Hashed k, v)]`. But I basically have no way to do that short of forking, because I can't see the constructors of `HashMap`.

There are probably a bunch of other cases where I'd like to implement some specific functionality that doesn't belong upstream in `unordered-containers`, but would benefit from being able to import the internals.

**Comment by jamespayor** [comment]
To be clear, my initial proposal would be:

```cabal
library
  exposed-modules:
    Data.HashMap.Lazy
    Data.HashMap.Strict
    Data.HashMap.Base
    Data.HashMap.Strict.Base
    Data.HashSet
    Data.HashSet.Base
  other-modules:
    Data.HashMap.Array
    Data.HashMap.List
    Data.HashMap.Unsafe
    Data.HashMap.UnsafeShift
```

**Comment by jamespayor** [comment]
Another option I prefer less, but would enable some of the thing I'm after, is:

```cabal
library
  exposed-modules:
    Data.HashMap.Lazy
    Data.HashMap.Strict
    Data.HashSet
    Data.HashSet.Internal
    Data.HashMap.Internal
  other-modules:
    Data.HashMap.Array
    Data.HashMap.Base
    Data.HashMap.Strict.Base
    Data.HashMap.List
    Data.HashMap.Unsafe
    Data.HashMap.UnsafeShift
    Data.HashSet.Base
```
... where `Data.HashMap.Internal` and `Data.HashSet.Internal` are new modules that re-export the constructors of `HashMap` and `HashSet` respectively, and other internals. This seems fairly ugly though, and less simple than giving downstream users access to the internals that they may abuse at their own peril =)

**Comment by sjakobi** [comment]
Great timing, @jamespayor! :)

Just today I made a proposal for exposing more internals in https://github.com/haskell-unordered-containers/unordered-containers/issues/211#issuecomment-652484700.

How about you chime in there and we close this issue here as a duplicate!?

**Comment by jamespayor** [comment]
Wow. Okay, I'll move the relevant points across.
(Closing duplicate issue.)
