### ISSUE TITLE
alterF: No need to delete when the key is absent?!

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#287]
https://github.com/haskell-unordered-containers/unordered-containers/blob/6f1a92f6cc9fe817661ba5dc56bf609a5145d683/Data/HashMap/Internal.hs#L1279-L1286

When `fres` is `Nothing`, we `delete'` `k` from `m` no matter whether `m` contained `k` in the first place. We could skip the deletion though if `mv` is `Nothing`.

I'm surprised that the code doesn't already do that. Are there reasons against doing it?

**Comment by treeowl** [comment]
You're totally right. Someone goofed, and it was probably me. `lens` says

```haskell
instance (Eq k, Hashable k) => At (HashMap k a) where
  at k f m = f mv <&> \r -> case r of
    Nothing -> maybe m (const (HashMap.delete k m)) mv
    Just v' -> HashMap.insert k v' m
    where mv = HashMap.lookup k m
  {-# INLINE at #-}
```

and that looks right. Have you checked `IntMap` for this?

**Comment by sjakobi** [comment]
Thanks for the quick response, @treeowl, and no worries! :)

`IntMap` seems to be fine – it already uses the `maybe m ... delete` pattern both for the lazy and he strict version.

**Comment by sjakobi** [comment]
Fix is up in https://github.com/haskell-unordered-containers/unordered-containers/pull/288.
