### ISSUE TITLE
What's the memory usage of HashMap?

### ISSUE THREAD

**Issue by nh2** [haskell-unordered-containers/unordered-containers#312]
@tibbe once wrote two blog posts on this topic:

* [Computing the size of a HashMap](http://blog.johantibell.com/2011/06/computing-size-of-hashmap.html) and [Memory footprints of some common data types](http://blog.johantibell.com/2011/06/memory-footprints-of-some-common-data.html) stating:
  > 5N + 4(N-1) words + size of keys & values

This blog post was also turned into a HaskellWiki article afterwards:

* https://wiki.haskell.org/GHC/Memory_Footprint stating:
  > 4.5N words + N * (sizeof(k) + sizeof(v))

However, these two **sources disagree significantly on the memory usage** of `HashMap`/`HashSet` (9N vs 4.5N).

Who is right?

The wiki was changed by @tibbe himself in this revision: https://wiki.haskell.org/index.php?title=GHC/Memory_Footprint&diff=54685&oldid=54684

Was there a change made to `unordered-containers` that explains this size reduction?

**Comment by sjakobi** [comment]
Note that the `HashMap` declaration in http://blog.johantibell.com/2011/06/computing-size-of-hashmap.html is different from the current one. Also note this comment at the end of the same blog post:

> Aside: I'm working on switching HashMap to use another data structure, a Hash Array Mapped Trie, in its implementation. This will bring the overhead per key-value pair down from 9 words to about 4 words.

The declaration in the code was changed in https://github.com/haskell-unordered-containers/unordered-containers/commit/aca017eb197953692d43cf937fc11d8ee22ea12f, so I assume that the formula used in the wiki is correct.

**Comment by nh2** [comment]
Ah, that makes sense.

I was misled by the fact that the commit is from `Jan 20, 2011`, but the post from later (June the same year), so I assumed it must be a change later than that.
