### ISSUE TITLE
Why is there an `Ord` instance?

### ISSUE THREAD

**Issue by konsumlamm** [haskell-unordered-containers/unordered-containers#350]
The documentation for the `Ord (HashMap k v)` instance says:

> The ordering is total and consistent with the Eq instance. However, nothing else about the ordering is specified, and it may change from version to version of either this package or of hashable.

This makes it seem like a pretty useless instance, so I wonder why it exists in the first place?

**Comment by treeowl** [comment]
Lets them be stored in `Set`s, used as `Map` keys, etc.

**Comment by konsumlamm** [comment]
Hmm, I don't find that a very convincing reason, as I can't think of many applications for using a hashmap/hashset in a map/set key...

**Comment by treeowl** [comment]
The fact you don't find it useful is not a reason to remove it.

**Comment by konsumlamm** [comment]
Fair.
