### ISSUE TITLE
Make use of `shrinkSmallMutableArray#` primop

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#362]
Since GHC 8.10 there is a [`shrinkSmallMutableArray#`](https://hackage.haskell.org/package/base-4.14.0.0/docs/GHC-Exts.html#v:shrinkSmallMutableArray-35-) primop that may be useful for functions like `filter` and `mapMaybe`. It would allow us to perform deletions in-place instead of creating a new array.

**Comment by treeowl** [comment]
Ooh, good thinking!

**Comment by sjakobi** [comment]
We may be able to use it wherever we're currently using `trim`:

https://github.com/haskell-unordered-containers/unordered-containers/blob/d4e31f6169bfb31a4c539066f0f47e2c0889cd51/Data/HashMap/Internal/Array.hs#L295-L298

**Comment by sjakobi** [comment]
#406 has introduced `shrink`:

https://github.com/haskell-unordered-containers/unordered-containers/blob/d24cc1f48cef1c7f6bc041e7e73ee40a1fc7b731/Data/HashMap/Internal/Array.hs#L210-L222

So far it's only used in `intersection[With[Key]]` though.

**Comment by sjakobi** [comment]
With #433 we're using `shrink` in `filter` and `mapMaybe` now. #435 refactors `updateOrConcatWithKey` to use `shrink`. I can't find any obvious other spots where `shrink` would be useful.

**Comment by sjakobi** [comment]
For reference: some performance aspects of `shrinkSmallMutableArray#` are still unclear: https://github.com/haskell-unordered-containers/unordered-containers/issues/441
