### ISSUE TITLE
Use "smart initialization" trick in more places

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#363]
https://github.com/haskell-unordered-containers/unordered-containers/pull/359 introduced a trick that replaces a write to an array by initializing the array with the same element. We can use the same trick in some more places:

* [x] `insertNewKey.snocNewLeaf` (#407): https://github.com/haskell-unordered-containers/unordered-containers/blob/f59bb2601204ac37abcc460eb04c7227340a8805/Data/HashMap/Internal.hs#L828-L833
* [x] `insertModifyingArr` (#407) : https://github.com/haskell-unordered-containers/unordered-containers/blob/f59bb2601204ac37abcc460eb04c7227340a8805/Data/HashMap/Internal.hs#L1008-L1025
* [x] `updateOrSnocWithKey` (#407) : https://github.com/haskell-unordered-containers/unordered-containers/blob/f59bb2601204ac37abcc460eb04c7227340a8805/Data/HashMap/Internal.hs#L2161-L2178
* [ ] `Strict.updateOrSnocWithKey`

**Comment by konsumlamm** [comment]
Just a thought: It might be worth documenting this trick (and other, similar ones) in `CONTRIBUTING.md`, so that people use it in their contributions and understand the existing uses.

**Comment by konsumlamm** [comment]
I'm not really familiar with GHC's NOTE system. If there's a way to look at the notes other than reading the source code, then that's great! If the notes were only available in the source code, I think that wouldn't be very discoverable.

**Comment by sjakobi** [comment]
I think it's an advantage of GHC-style notes that they are located so closely to the code. This way the surrounding code provides context which is helpful for understanding the note.

**Comment by sjakobi** [comment]
Regarding the code patterns from the issue description. I think all of these could be refactored to use a new `Array.snoc` operation.

```haskell
snoc :: Array a -> a -> Array a
```

**Comment by sjakobi** [comment]
One task left: `Strict.updateOrSnocWithKey`
