### ISSUE TITLE
Space leaks in `union[With[Key]]` due to lazy application of combining function on collisions

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#379]
The problem is in line 2206 in `updateOrConcatWithKey` which is used to combine `Collisions` arrays in `unionWithKey`, including the strict variant:

https://github.com/haskell-unordered-containers/unordered-containers/blob/f1ea9a420746405df181832bb4a8499a97fb8514/Data/HashMap/Internal.hs#L2184-L2213

I haven't constructed a reproducer yet, but I think the following functions are affected:

* In `union`, a reference to `v2` is unnecessarily retained – we only truly need `v1`. (Ideally, we'd avoid the entire read from `ary2` and simply use the entire `Leaf` from `ary1`.)
* In `Strict.unionWith[Key]`, the values resulting from the combining function applied to `Collisions` elements are not evaluated to WHNF as promised.

**Comment by sjakobi** [comment]
Regarding `union`, I should add that we're also exporting this function from `Data.HashMap.Strict` where it breaks the promise that all values will be in WHNF.

**Comment by sjakobi** [comment]
For reference: https://github.com/haskell-unordered-containers/unordered-containers/issues/254 was a similar issue.

**Comment by treeowl** [comment]
I don't think we want to promise that all values in the result of `union` will be in WHNF. That would slow down all code that uses `Strict.union` just for taking unions rather than for taking unions and forcing everything.

**Comment by sjakobi** [comment]
Yeah. In the `union` of two maps produced with the `Strict` API all values should be in WHNF though, right?!

**Comment by sjakobi** [comment]
Actually, I think `Lazy.unionWith` is affected too: The thunk resulting from the application of the combining function shouldn't retain a reference to the key `k` but it does.
