### ISSUE TITLE
Add sequence containers?

### ISSUE THREAD

**Issue by oberblastmeister** [haskell-unordered-containers/unordered-containers#418]
I have a persistent vector implementation, and there is also [rrb-vector](https://github.com/konsumlamm/rrb-vector). Would it make sense to add them to `unordered-containers`? For example `containers` has `Data.Sequence`. It would be nice to have a sequence data structure also. Even though it is called unordered, I think it makes sense because they are both array based and have the same trie structure.

**Comment by konsumlamm** [comment]
What is unordered about a vector/sequence container? The name of this package is **unordered**-containers after all. If anything, I think it would make sense to add more sequence types (with different tradeoffs) to `containers`.

**Comment by sjakobi** [comment]
Personally, I'm not very keen on maintaining more code than I already do, particularly code that has no existing users.

In this case I also don't see why these persistent vectors would be a particularly good fit for this package.

If you want to publish your code, I think you can simply release it as a new package.

**Comment by sjakobi** [comment]
For reference: The persistent vector implementation is now on Hackage: https://hackage.haskell.org/package/pvector

Congrats, @oberblastmeister! :)
