### ISSUE TITLE
Check effect of shrinking on non-moving collector

### ISSUE THREAD

**Issue by treeowl** [haskell-unordered-containers/unordered-containers#441]
When the non-moving garbage collector is in use, each shrink operation has to do some funny business to support it. How expensive is this? Is it expensive enough to justify cloning instead, especially for very small arrays?

**Comment by treeowl** [comment]
@bgamari, your input would be very much appreciated.

**Comment by sjakobi** [comment]
To provide a single datapoint: The 8% speedup as a result of using `shrink` in `filterMapAux` (https://github.com/haskell-unordered-containers/unordered-containers/pull/433) was measured with `-nonmoving-gc`:

https://github.com/haskell-unordered-containers/unordered-containers/blob/fe33c6024e412a28acdc09693e242ed0bbdf734b/unordered-containers.cabal#L138-L139

> When the non-moving garbage collector is in use, each shrink operation has to do some funny business to support it.

Roughly what is this funny business? I'm very unfamiliar with how the non-moving GC works.

**Comment by treeowl** [comment]
Roughly, I have no idea. I just saw calls to some functions or macros in the cmm definition of the shrinking primop. How did it do with the copying collector?

**Comment by sjakobi** [comment]
> How did it do with the copying collector?

I didn't try that. Something like `cabal run benches -- -p filterWithKey --stdev 0.5` should do the trick.

**Comment by treeowl** [comment]
It would be interesting to see, but shrinking is pretty much totally free with that collector, so I imagine the improvements would be even larger.

**Comment by treeowl** [comment]
If the code was faster than before when you tested with the non-moving collector, I think we can close this.

**Comment by sjakobi** [comment]
Alright.
