### ISSUE TITLE
Redundant `Hashable` constraints on `intersection*` and `union*`

### ISSUE THREAD

**Issue by sjakobi** [haskell-unordered-containers/unordered-containers#443]
These functions don't compute any hashes, so we could consider removing the redundant constraints.

**Comment by treeowl** [comment]
Yank them, as far as I'm concerned. Did the previous `intersection` implementation need that?

**Comment by sjakobi** [comment]
> Did the previous `intersection` implementation need that?

Yeah. It was based on `unsafeInsert`, so it was re-computing hashes.
