### ISSUE TITLE
Maintain CHANGELOG

### ISSUE THREAD

**Issue by andreasabel** [haskell-unordered-containers/unordered-containers#85]
Please journal changes in a CHANGELOG.  
Makes it much easier to decide whether new versions of unordered-containers are likely to work out-of-the-box, and upper bounds on version constraints can be safely relaxed.

**Comment by sjakobi** [comment]
[`CHANGES.md`](https://github.com/haskell-unordered-containers/unordered-containers/blob/master/CHANGES.md) has actually existed for quite a while already!
