### ISSUE TITLE
`alter` and other functions?

### ISSUE THREAD

**Issue by gibiansky** [haskell-unordered-containers/unordered-containers#89]
The old `hashmap` package (here: http://hackage.haskell.org/package/hashmap-1.3.0.1/docs/Data-HashMap.html) has an `alter` function. Is there a particular reason that `unordered-containers` doesn't? It's very useful! 

In particular, it would be really nice if `Data.HashMap` exported closer to the set of functions provided by `Data.Map`, so you could easily swap in different implementations by changing an import statement. (Of course, that would change a lot of behaviour and typeclass constraints, but still.)

**Comment by sjakobi** [comment]
`alter` has been added in #90. If there's demand for more additions I'd suggest to bring this up in a new issue.
